# Generated by Django 5.0.6 on 2024-06-03 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 10, 1, 33, 344276))),
                ('updated', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 10, 1, 33, 344276))),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('storyline', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 10, 1, 33, 344276))),
                ('updated', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 10, 1, 33, 344276))),
            ],
        ),
    ]
