# Generated by Django 5.0.6 on 2024-06-03 06:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0002_alter_streamplatform_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='watch_list.streamplatform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 42, 52, 6642)),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 42, 52, 6642)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 42, 52, 6642)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 42, 52, 6642)),
        ),
    ]
