# Generated by Django 5.0.6 on 2024-06-03 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0003_watchlist_platform_alter_streamplatform_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 43, 31, 862637)),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 43, 31, 862637)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 43, 31, 862637)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 43, 31, 862637)),
        ),
    ]
