# Generated by Django 5.0.6 on 2024-06-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0004_alter_streamplatform_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 44, 31, 354328)),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 44, 31, 354328)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 44, 31, 354328)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 44, 31, 354328)),
        ),
    ]
