# Generated by Django 5.0.6 on 2024-06-03 07:38

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0005_alter_streamplatform_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 12, 38, 3, 750250)),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 12, 38, 3, 750250)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 12, 38, 3, 750250)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 12, 38, 3, 750250)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 12, 38, 3, 750250))),
                ('updated', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 12, 38, 3, 750250))),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='watch_list.watchlist')),
            ],
        ),
    ]
